class Employe:
    def watch_videos(self):
        print("finctionality for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
class Erroradmin:
    def watch_videos(self):
        print("functionality for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
    def get_error(self):
        print("functionality for getting error")
        print("g")
        print("e")
        print("t")
        print("t")
        print("i")
        print("n")
        print("g")
        print("e")
        print("r")
        print("r")
        print("o")
        print("r")
        print("="*50)
        
class Superadmin:
    def watch_videos(self):
        print("functionality for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
    def get_error(self):
        print("functionality for getting error")
        print("g")
        print("e")
        print("t")
        print("t")
        print("i")
        print("n")
        print("g")
        print("e")
        print("r")
        print("r")
        print("o")
        print("r")
        print("="*50)
        
    def deleat_video(self):
        print("funtionality for deleating videos")
        print("d")
        print("e")
        print("l")
        print("e")
        print("a")
        print("t")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
one_obj = Employe()
two_obj = Erroradmin()
three_obj = Superadmin()

#method calling
one_obj.watch_videos()
two_obj.watch_videos()
two_obj.get_error()
three_obj. watch_videos()
three_obj.get_error()
three_obj.deleat_video()


#inheritance
                
        
                