class Student:
    def watch_videos(self):
        print("functionalitry for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
class Videoadmin:
    def watch_videos(self):
        print("functionalitry for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
    def add_videos(self):
        print("functionalitry for watching videos")
        print("a")
        print("d")
        print("d")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
class superadmin:
    def watch_videos(self):
        print("functionalitry for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
    def add_videos(self):
        print("functionalitry for watching videos")
        print("a")
        print("d")
        print("d")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
    def deleat_videos(self) :
        print("functionality for deleating videos") 
        print("d")
        print("e")
        print("l")
        print("e")
        print("a")
        print("t")
        print("i")
        print("n") 
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)    
        
obj_one = Student()
obj_two = Videoadmin()
obj_three = superadmin()

#method calling
obj_one.watch_videos()
obj_two.watch_videos()
obj_two.add_videos()
obj_three.watch_videos()
obj_three.add_videos()
obj_three.deleat_videos()

        
        
        
        
        