class Student:
    def watch_videos(self):
        print("="*50)
        print(" functionality for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
class Videoadmin:
    def watch_videos(self):
        print("="*50)
        print("finctionality fo watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
    def add_videos(self):
        print("=")
        print(" functionality for watching videos")
        print("="*50)
        print("a")
        print("d")
        print("d")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)

class superadmin:
    def watch_videos(self) : 
        print("="*50)
        print(" functionality for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)


    def add_videos(self):
        print("=")
        print(" functionality for adding videos")
        print("="*50)
        print("a")
        print("d")
        print("d")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)

    def deleat_videos(self):
        print("="*50)
        print("functionality for deleating videos")
        print("d")
        print("e")
        print("l")
        print("e")
        print("a")
        print("t")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
print ("Student user")
student_user = Student()
student_user.watch_videos()

print("video_admin_user")
video_admin_user = Videoadmin()
video_admin_user.watch_videos()
video_admin_user.add_videos()

print("super_admin_user")
super_admin_user = superadmin()
super_admin_user.watch_videos()
super_admin_user.add_videos()
super_admin_user.deleat_videos()

    