class Student:
    def watch_videos(self):
        print("="*50)
        print(" functionality for watching videos")
        print("w")
        print("a")
        print("t")
        print("c")
        print("h")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
class Videoadmin(Student):
    def add_videos(self):
        print("="*50)
        print(" functionality for watching videos")
        print("="*50)
        print("a")
        print("d")
        print("d")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
class superadmin(Videoadmin):
    def deleat_videos(self):
        print("="*50)
        print("funtionality for deleating videos")
        print("d")
        print("e")
        print("l")
        print("e")
        print("a")
        print("t")
        print("i")
        print("n")
        print("g")
        print("v")
        print("i")
        print("d")
        print("e")
        print("o")
        print("s")
        print("="*50)
        
print("student user")
student_user = Student()
student_user.watch_videos()

print("videp admin user")
video_admin_user = Videoadmin()
video_admin_user.watch_videos()
video_admin_user.add_videos()

print("super admin user")
super_admin_user = superadmin()
super_admin_user.watch_videos()
super_admin_user.add_videos()
super_admin_user.deleat_videos()
               
            